### ISSUE TITLE
Meta head service to scale up k8s cluster and down

### ISSUE THREAD

**Issue by rivernews** [rivernews/slack-middleware-server#78]
Currently there isn't an effective way to save cost when it comes to a k8s cluster that needs to keep up running, but being able to scale up largely AND save cost when idle. There're some components that are not easy to scale when using cheap VM size, thus forcing us need to use larger VM size for primary node pool, which kills the intention to save cost at least for idle state.

Another way to achieve this is to setup a head meta service that is totally free. Then, use this service to scale k8s cluster. Then k8s cluster can go for scaling scraper jobs.
- [x] Heroku free plan can be a good choice for this. The only downside using free plan is the initial cold call latency, could be up to 10 or 30 seconds. But after that it will work, and works well at least for the following 1 hour after each cold call. That's enough for us
  - [ ] Initial goal for this heroku head service can be, ability to scale up and down a k8s cluster, by triggering travis build. Basically we want to emulate the following commands that are currently run in local terminal manully:
    - [ ] API for running `python release.py -f` to scale up k8s cluster
    - [ ] API for running `local.auto.plan-and-apply.sh` to scale up SLK microservice. And perhaps other stuff like personal blog and appl tracky, but we can do them later, first priority is SLK.
    - [ ] API to scale down SLK and other services
    - [ ] API for running `python release.py -d`.
    - [ ] Porting these API and be able to trigger them via slack command. 
- [ ] Another thing we may try for heroku is to setup some kind of service warmer - that periodically sends request to services on heroku, let heroku worker keep accepting requests, so that it doesn't turn idle, and thus don't have that cold call latency issue anymore!

About the platform - we have many choices here:
- [ ] Continue to use node.js express, just like SLK. Fast for development. But if we want to use type system and Typescript, then there're some hussles that we need to implement.
- [ ] We may try some go web framework here, just to have a taste for what golang feels like when implementing it
  - [ ] Maybe we can even try out swagger, good API interactive documentation.
- [ ] Of course we can fall back to python Django, our old friend. 
- [ ] Java spring is also good, but I'd say there's not much incentive for doing so.
- [ ] Other language for web API service? Not much.

But after all this is not an urgent ticket, but an interesting one. We can still always run our local terminal, and we can go do other stuff. Not super bothering for now.

**Comment by rivernews** [comment]
Scaling up and down the entire k8 cluster, as well as SLK micro service, is done in https://github.com/rivernews/k8s-cluster-head-service.
